<div>
    <div class="bars">
        <?php foreach($data->sets as $bar) { ?>
            <div class="bar" style="<?php echo $bar->getBarStyle(); ?>">
                <div class="header">
                    <span class="complete"><?php echo $bar->complete; ?></span>
                    /
                    <span class="total"><?php echo $bar->total; ?></span>
                </div>
                <div class="view" style="height: <?php echo $bar->getHeight(); ?>px;"></div>
            </div>
        <?php } ?>
    </div>
        <?php foreach($data->sets as $bar) { ?>
            <div class="bar-title" style="<?php echo $bar->getLegendStyle(); ?>">
                <span class="title">
                    <?php echo $bar->title; ?>
                </span>
            </div>
        <?php } ?>
    <div style="clear:both;"></div>
</div>
